language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - php artisan key:generate
  - vendor/bin/phpunit
